# Generated by Django 2.2.9 on 2020-01-03 06:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('one_to_one', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Shop',
        ),
    ]
