# Generated by Django 2.2.9 on 2020-01-04 08:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('multitable', '0002_auto_20200103_1001'),
    ]

    operations = [
        migrations.AlterField(
            model_name='restaurant1',
            name='place1_ptr',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, related_name='restaurant1', related_query_name='restaurant1_by_oto', serialize=False, to='multitable.Place1'),
        ),
    ]
