# Generated by Django 2.2.9 on 2020-01-01 07:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_person_shrit_size'),
    ]

    operations = [
        migrations.RenameField(
            model_name='person',
            old_name='shrit_size',
            new_name='shirt_size',
        ),
    ]
