# Generated by Django 2.2.9 on 2020-01-03 05:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('many_to_many', '0005_auto_20200102_1236'),
    ]

    operations = [
        migrations.AlterField(
            model_name='instagramuser',
            name='following',
            field=models.ManyToManyField(related_name='followers', through='many_to_many.Relation', to='many_to_many.InstagramUser'),
        ),
    ]
